logging:
  level:
    org.springframework: DEBUG
    com.subbu.ibot: DEBUG
    com.github.seratch: DEBUG

ibot:
  slack:
    accessToken: <please put your accessToken here>
    botAccessToken: <please put your botAccessToken here>
    signingSecret: <please put your signingSecret here>

management:
  endpoints:
    web:
      exposure:
        include: '*'